"""added email to user

Revision ID: 47627e51fa32
Revises: 63b7e055decf
Create Date: 2020-10-30 15:14:06.091281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47627e51fa32'
down_revision = '63b7e055decf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
