"""Add favourites model

Revision ID: 5afea7fc8eb5
Revises: b8289f8849f5
Create Date: 2020-11-06 16:50:11.575912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afea7fc8eb5'
down_revision = 'b8289f8849f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('fcst_models', schema=None) as batch_op:
        batch_op.alter_column('arima_d',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('arima_p',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('arima_q',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_joined_at'), ['joined_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_joined_at'))

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fcst_models', schema=None) as batch_op:
        batch_op.alter_column('arima_q',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('arima_p',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('arima_d',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_stock_id'))

    op.drop_table('favourite')
    # ### end Alembic commands ###
