"""change user.email to joined_at

Revision ID: 63b7e055decf
Revises: 0d18e7e5d6d4
Create Date: 2020-10-27 02:16:15.229659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b7e055decf'
down_revision = '0d18e7e5d6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
